#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process.
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process exists
if [ -n "$pid" ]; then
	    # Use kill to stop the process
	        kill "$pid" && echo "Terminated"
	else
		    echo "Process not found."
fi
