#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process.
pid=$(pgrep -f "7-highlander")

# Check if the process exists
if [ -n "$pid" ]; then
    # Use pkill to stop the process
    pkill -f "7-highlander"
else
    echo "Process not found."
fi
