#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
trap 'echo "I am invincible!!!"' SIGTERM

# Loop indefinitely, displaying "To infinity and beyond" with a sleep 2 in between each iteration
while true; do
    echo "To infinity and beyond"
    sleep 2
done
