#!/usr/bin/env bash
# kills the process 7-highlander
pid=$(pgrep -f "7-highlander")

# Check if the process exists
if [ -n "$pid" ]; then
    # Use kill to stop the process
    kill -9 "$pid"
else
    echo "Process not found."
fi
