#!/usr/bin/env bash
# Displays Best school 10times using until loop
# Initialize counter
counter=0

# Execute loop until counter reaches 10
until [ $counter -ge 10 ]; do
    echo "Best School"
    # Increment counter
    ((counter++))
done
