#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

counter=0

while [ $counter -lt 12 ]; do
	echo "Hour: $counter"

	j=1
	while [ $j -le 59 ]; do
		echo "$j"
		((j++))
	done
	((counter++))
done
